// 腾讯云图片地址
// export const guideBg = 'cloud://qyctaro-f7ica.7179-qyctaro-f7ica/Onboarding3.png'
// export const avatar = 'cloud://qyctaro-f7ica.7179-qyctaro-f7ica/avatar.jpg'
// export const sceneryImg ='cloud://qyctaro-f7ica.7179-qyctaro-f7ica-1259797475/501555767652_.pic_hd.jpg'
// export const cameraIcon  = 'cloud://qyctaro-f7ica.7179-qyctaro-f7ica/camera.png'
// export const collectIcon = 'cloud://qyctaro-f7ica.7179-qyctaro-f7ica/heart.png'
// export const collectIconGray = 'cloud://qyctaro-f7ica.7179-qyctaro-f7ica/Like@3x.png'
// export const CombinedIcon = 'cloud://qyctaro-f7ica.7179-qyctaro-f7ica/Combined.png'
// export const colorWavy = 'cloud://qyctaro-f7ica.7179-qyctaro-f7ica/Waves@2x.png'
 export const shareCard ='cloud://qyctaro-f7ica.7179-qyctaro-f7ica/card1.jpg'
 export const shareCard1 = 'cloud://qyctaro-f7ica.7179-qyctaro-f7ica/cardShare.jpg'
// https://ibb.co/WfMNFQv  网站ibb库图片
// export const cameraIcon ='https://i.ibb.co/NKJgpX2/501555767652-pic-hd.jpg'
// export const weixinIcon = 'https://i.ibb.co/svjVCyY/image.png'
// export const friendsIcon = 'https://i.ibb.co/KXZS8T0/image.png'
// export const closeIcon = 'https://i.ibb.co/7g0mzGY/image.png'

// QQ空间图地址
export const guideBg = 'http://r.photo.store.qq.com/psb?/V14bWx4d2PomPS/gC7Ql6JK6oAGXdnmNVBSnLlEeUeMe9mIn8trKbswpKA!/r/dIUBAAAAAAAA'
export const avatar = 'http://m.qpic.cn/psb?/V14bWx4d2PomPS/1iHlOQQlQp2UacKzvQM255MWzuILt4riEdXFko7vlyA!/b/dIMAAAAAAAAA&bo=oQQ4BAAAAAARF7k!&rf=viewer_4'
export const sceneryImg ='http://m.qpic.cn/psb?/V14bWx4d2PomPS/aRs*h1xVigMdwOJBqQLgVZ2UXY59OWOIEVPiB8quHS4!/b/dFIBAAAAAAAA&bo=VAY4BAAAAAARF04!&rf=viewer_4'
export const sceneryImg1 = 'http://m.qpic.cn/psb?/V14bWx4d2PomPS/vZcTXOZSO5hiQ*QD1nxkIzXikEOe3xU9ZiLVs2E8NfE!/b/dL8AAAAAAAAA&bo=UwY4BAAAAAARB1k!&rf=viewer_4'
export const sceneryImg2 = 'http://m.qpic.cn/psb?/V14bWx4d2PomPS/1HQnGRr.9A8fIz1rbGuonDBESH9UUZbxxyBEGfalZLI!/b/dMUAAAAAAAAA&bo=UwY4BAAAAAARJ3k!&rf=viewer_4'
export const sceneryImg3 = 'http://m.qpic.cn/psb?/V14bWx4d2PomPS/.Fqwzhixx8J8kd55WsfQnrXUqBc0eT3Psd5CyuKBDLo!/b/dL8AAAAAAAAA&bo=1ALjAQAAAAARFxQ!&rf=viewer_4'
export const cameraIcon  = 'http://m.qpic.cn/psb?/V14bWx4d2PomPS/X05DrcwGmFV0DLC3SHbi1WywIZG1BwaMoKbuUU0UUSQ!/b/dLgAAAAAAAAA&bo=TgBKAAAAAAADFzY!&rf=viewer_4'
export const collectIcon = 'http://m.qpic.cn/psb?/V14bWx4d2PomPS/ov42o6IlMG1Z8.C.Vu11JvrEegGdf2hCs05M6Lwh2tA!/b/dL8AAAAAAAAA&bo=IAAeAAAAAAADBxw!&rf=viewer_4'
export const CombinedIcon = 'http://m.qpic.cn/psb?/V14bWx4d2PomPS/N*jTFtGTRVEUcjr9.DU8IT358Iwu3.1nGXl8sL*Yx1g!/b/dFIBAAAAAAAA&bo=IAAgAAAAAAADFzI!&rf=viewer_4'
export const colorWavy = 'http://m.qpic.cn/psb?/V14bWx4d2PomPS/WSoOnOsZEQbA8KVxuTEHZkJbUoQiC6B3zq6ChImSzo0!/b/dL4AAAAAAAAA&bo=7gLOAAAAAAADBwA!&rf=viewer_4'
export const collectIconGray = 'http://m.qpic.cn/psb?/V14bWx4d2PomPS/axDb0I8BgEJUVPiTe8yRqr7G26IWPxfcMOrupAq2KUw!/b/dL8AAAAAAAAA&bo=MAAtAAAAAAADBz8!&rf=viewer_4'
export const weixinIcon = 'http://r.photo.store.qq.com/psb?/V14bWx4d2PomPS/SV5uwV6A8j33luoYHh1SXOdCOFtADPNaaO.zGAwm6Fs!/r/dL8AAAAAAAAA'
export const friendsIcon = 'http://r.photo.store.qq.com/psb?/V14bWx4d2PomPS/BkeotRzTZBxoXsbofkgxrM6B14AQy5zzWE*nul*cGFo!/r/dFQBAAAAAAAA'
export const closeIcon = 'http://r.photo.store.qq.com/psb?/V14bWx4d2PomPS/aCIccr43SciShdRuTaBeQXspDB2XDF9Ivnz0e3C0v*c!/r/dL4AAAAAAAAA'
